# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='title',
        ),
    ]
